import Footer from "@/app/components/layout/Footer";
import { Metadata } from "next";

import { Toaster } from "react-hot-toast";
import Provider from "./Provider";
import Header from "./components/layout/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: {
    default: "Ecommerce",
    template: `%s | Store`,
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Provider>
        <body>
          <Header />
          <Toaster />
          <main className="max-w-7xl mx-auto p-5 min-h-screen pt-28">
            {children}
          </main>
          <Footer />
        </body>
      </Provider>
    </html>
  );
}
